module.exports = {
  content: ['./App.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    colors: {
      white: 'var(--color-white)',
      black: 'var(--color-black)',
      primary: {
        50: 'var(--color-primary-50)',
        100: 'var(--color-primary-100)',
        200: 'var(--color-primary-200)',
        300: 'var(--color-primary-300)',
        400: 'var(--color-primary-400)',
        500: 'var(--color-primary-500)',
        600: 'var(--color-primary-600)',
        700: 'var(--color-primary-700)',
        800: 'var(--color-primary-800)',
        900: 'var(--color-primary-900)',
      },
      blue: {
        50: 'var(--color-blue-50)',
        100: 'var(--color-blue-100)',
        200: 'var(--color-blue-200)',
        300: 'var(--color-blue-300)',
        400: 'var(--color-blue-400)',
        500: 'var(--color-blue-500)',
        600: 'var(--color-blue-600)',
        700: 'var(--color-blue-700)',
        800: 'var(--color-blue-800)',
        900: 'var(--color-blue-900)',
      },
      warning: {
        50: 'var(--color-warning-50)',
        100: 'var(--color-warning-100)',
        200: 'var(--color-warning-200)',
        300: 'var(--color-warning-300)',
        400: 'var(--color-warning-400)',
        500: 'var(--color-warning-500)',
        600: 'var(--color-warning-600)',
        700: 'var(--color-warning-700)',
        800: 'var(--color-warning-800)',
        900: 'var(--color-warning-900)',
      },
      error: {
        50: 'var(--color-error-50)',
        100: 'var(--color-error-100)',
        200: 'var(--color-error-200)',
        300: 'var(--color-error-300)',
        400: 'var(--color-error-400)',
        500: 'var(--color-error-500)',
        600: 'var(--color-error-600)',
        700: 'var(--color-error-700)',
        800: 'var(--color-error-800)',
        900: 'var(--color-error-900)',
      },
      neutral: {
        50: 'var(--color-neutral-50)',
        100: 'var(--color-neutral-100)',
        200: 'var(--color-neutral-200)',
        300: 'var(--color-neutral-300)',
        400: 'var(--color-neutral-400)',
        500: 'var(--color-neutral-500)',
        600: 'var(--color-neutral-600)',
        700: 'var(--color-neutral-700)',
        800: 'var(--color-neutral-800)',
        900: 'var(--color-neutral-900)',
        950: 'var(--color-neutral-950)',
      },
      surface: {
        light: 'var(--color-surface-light)',
        deep: 'var(--color-surface-deep)',
        dark: 'var(--color-surface-dark)',
        medium: 'var(--color-surface-medium)',
        raised: 'var(--color-surface-raised)',
      },
      tab: {
        active: 'var(--color-tab-active)',
        inactive: 'var(--color-tab-inactive)',
        background: 'var(--color-tab-background)',
      },
      finance: {
        income: 'var(--color-income)',
        expense: 'var(--color-expense)',
        savings: 'var(--color-savings)',
      },
      bg: 'var(--color-bg)',
      'secondary-bg': 'var(--color-secondary-bg)',
      card: 'var(--color-card)',
      'secondary-card': 'var(--color-secondary-card)',
      pill: 'var(--color-pill)',
      title: 'var(--color-title)',
      text: 'var(--color-text)',
      'text-muted': 'var(--color-text-muted)',
      'text-tertiary': 'var(--color-text-tertiary)',
      border: 'var(--color-border)',
      progress: 'var(--color-progress)',
      'progress-bar': 'var(--color-progress-bar)',
    },
    fontFamily: {
      poppins: ['Poppins'],
      arial: ['Arial'],
    },
    spacing: {},
  },
  darkMode: 'media',
  plugins: [],
};
